project/urls.py
from django.contrib import admin
from django.urls import path, include
from cars import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', views.main, name='main'),
    path('', views.main),
    path('cars/<int:id>/', views.obzor, name='obzor'),
    path('workspace/', include('workspace.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

workspace/urls.py
from django.urls import path
from workspace import views


urlpatterns = [
    path('', views.main, name='workspace'),
    path('create/', views.create, name='create'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('update/<int:id>', views.update, name='update')
]

cars/models.py
from django.db import models

class Category(models.Model):
    class Mate:
        verbose_name = 'Категория'
        verbose_name_populer = 'Категории'

    name_category = models.CharField(max_length = 10, verbose_name = 'Марка')

    def __str__(self):  
        return f'{self.id}) {self.name_category}'


class Cars(models.Model):

    class Mate:
        verbose_name = 'Маркa'
        verbose_name_populer = 'Марки'
        

    name = models.CharField(max_length = 50, verbose_name = 'Марка')
    photo = models.ImageField(verbose_name='Фото', upload_to='imgs/')
    volume = models.CharField(max_length = 3, verbose_name = 'Объем')
    model = models.CharField(max_length = 20, verbose_name = 'Модель')
    info = models.TextField(verbose_name = 'Информация')
    data = models.DateField(verbose_name = 'Дата создания', auto_now_add = True)
    updata = models.DateField(verbose_name = 'Изменить дату', auto_now = True)
    price = models.CharField(max_length = 12,verbose_name = 'Цена')
    category = models.ForeignKey('Category', on_delete = models.PROTECT, related_name='cars', verbose_name='категория')
    teg = models.ManyToManyField('cars.Hesh', related_name='cars', verbose_name='теги', blank=True)
    views = models.IntegerField(default=0, verbose_name = 'Просмотры')
    is_publish = models.BooleanField(verbose_name = 'публикация', default = True)

    
    def __str__(self):
        return f'{self.id}) {self.name}'
    

class Hesh(models.Model):
    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'
    
    name = models.CharField(max_length=100, verbose_name='название')
    
    def __str__(self):
        return self.name


class NetWorkLink(models.Model):

    cars = models.OneToOneField('cars.Cars', on_delete=models.CASCADE, related_name='link')
    name= models.CharField(max_length = 30,verbose_name = 'название')
    name_link = models.CharField(max_length = 40, verbose_name = 'ссылка')
    

    def __str__(self):
        return self.name

workspace/forms.py
from django import forms
from cars.models import Cars, Category, Hesh
import re
from django.core.exceptions import ValidationError
        
class CarCreate(forms.ModelForm):
    class Meta:
        model = Cars
        fields = ['name', 'photo', 'volume', 'model', 'info', 'price', 'category', 'teg', 'is_publish']

        widgets = {
            'name': forms.TextInput(attrs={'placeholder':'Название', 'class':'mb-2 border-b border-gray-400 outline-none pl-1'}), 
            'volume': forms.TextInput(attrs={'placeholder':'Объем', 'class':'mb-2 border-b border-gray-400 outline-none pl-1'}),
            'model': forms.TextInput(attrs={'placeholder':'Модель', 'class':'mb-2 border-b border-gray-400 outline-none pl-1'}),
            'info': forms.Textarea(attrs={'placeholder':'Write....', 'class':'mb-2 border outline-none flex'}),
            'price': forms.TextInput(attrs={'placeholder':'Цена', 'class':'mb-2 border-b border-gray-400 outline-none pl-1'}),
        }

    # def clean_name(self):
    #     name = self.cleaned_data['name']
    #     if re.match(r'\d', name):
    #         raise ValidationError('Название не далжно начинаться с цифры')
    #     return name
        

cars/views.py
from django.shortcuts import render
from cars.models import Cars, Category, Hesh

def main(request):
    cars = Cars.objects.all()

    search = request.GET.get('search')
    if search:
        cars = cars.filter(name__icontains=search)

    category = request.GET.get('category')
    if category:
        category = Category.objects.get(id=int(category))
        cars = cars.filter(category=category)
    
    category_list = Category.objects.all()
    return render(request, 'index.html', {'cars' : cars, 'category_list' : category_list})

def obzor(request, id):
    cars = Cars.objects.get(id=id)
    cars.views += 1
    cars.save()
    category_list = Category.objects.all()
    return render(request, 'obzor.html', {'cars': cars, 'category_list': category_list})



'контекст'
'queryparams'

workspace/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cars.models import Cars
from workspace.forms import CarCreate

def main(request):
    cars = Cars.objects.all()

    return render(request, 'workspace/body.html', {'cars':cars})


def create(request):
    form = CarCreate()
    if request.method == 'POST':
        form = CarCreate(data=request.POST, files=request.FILES)
        if form.is_valid():
            car = form.save()
            
        return redirect('/workspace/')


    return render(request, 'workspace/create.html', {'form':form})

def update(req, id):
    car = get_object_or_404(Cars, id=id)
    if req.method == 'POST':
        form = CarCreate(data=req.POST, files=req.FIELS, instance=car)
        if form.is_valid():
            car = form.save()
            return redirect('/workspace/')

    else:
        form = CarCreate(instance=car)

    return render(req, 'workspace/update.html', {'form':form, 'car': car})

def delete(req, id):
    car = Cars.objects.get(id=id)
    car.delete()

    return redirect('/workspace/')

templates/components/nav.html
{% load static %}
<link rel="stylesheet" href="{% static "css.css" %}">

<nav class="nav">
    <div class="container">
        <div class="nav-body">
            <from class="glav-from" method="GET">
                <button class="glav" type="submit">AVTO RYNOK</button>
            </from>
            <div class="search">
                <form class="search-from" method="GET">
                  <input class="search-input" type="search" name="search" value="{{request.GET.search}}" placeholder="Search" aria-label="Search">
                  <button class="search-button" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</nav>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css.css" %}">
  </head>
  <body>
    {% include "components/nav.html" %}

    <div class="container">

      <div class="block">

        {% comment %} <label for="categories">Категория:</label> {% endcomment %}
        {% comment %} <select id="categories" name="search">
          <option value="{% url 'main' %}?category=''">Все</option>
          {% for marka in category_list %}
            <option ="{% url 'main' %}?category={{marka.id}}">{{marka.name_category}}</option>
          {% endfor %}
        </select> {% endcomment %}
        <a href="{% url 'main' %}">Home</a>
        {% for marka in category_list %}
            <a href="{% url 'main' %}?category={{marka.id}}">{{marka.name_category}}</a>
        {% endfor %}
        <a href="{% url 'workspace' %}">Workspace</a>
      </div>

      <div class="cards">
        {% for item in cars %}
        <div class="fon">
          <div class="font">
            <img src="{{ item.photo.url }}" class="card-img-top" alt="..." />
            <h1>{{item.name}}</h1>
            <p class="ccn">{{cars.category.name}}</p>
            <h4>Объем двигателя: {{item.volume}}</h4>

            {% for teg in item.teg.all %}
              <a href="#">{{teg.name}}</a>
            {% endfor %}

              <a href="{{item.link.name_link}}">{{item.link.name}}</a>
            
              <h4>Просмотры {{item.views}}</h4>
            <div class="btn">
              <button class='btn2'>
                <a href="{% url 'obzor' id=item.id %}" class="ash">Обзор</a>
              </button>
              <h2>Цена: {{item.price}} р</h2>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </body>
</html>

templates/obzor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/workspace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Workspace</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    {% include "components/nav.html" %}
    {% block cards %}{% endblock cards %}
    {% block create %}{% endblock create %}
    {% block update %}{% endblock update %}
</body>
</html>

templates/workspace/body.html
{% extends "workspace/base.html" %} 
{% block cards %}
<p class='flex items-end justify-end mt-10 mr-20'>
    <a href="{% url 'create' %}"><button class='btn2'>Create</button></a>
</p>
<div class="cards">
  {% for item in cars %}
  <div class="fon">
    <div class="font">
      <a href="{% url "delete" id=item.id %}">Delete</a>
      <a href="{% url "update" id=item.id %}">Update</a>
      <img src="{{ item.photo.url }}" class="card-img-top" alt="" />
      <h1>{{item.name}}</h1>
      <p class="ccn">{{cars.category.name}}</p>
      <h4>Объем двигателя: {{item.volume}}</h4>

      {% for teg in item.teg.all %}
      <a href="#">{{teg.name}}</a>
      {% endfor %}

      <a href="{{item.link.name_link}}">{{item.link.name}}</a>

      <h4>Просмотры {{item.views}}</h4>
      <div class="btn">
        <button class='btn2'>
          <a href="{% url 'obzor' id=item.id %}" class="ash">Обзор</a>
        </button>
        <h2>Цена: {{item.price}} р</h2>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock cards %} 


templates/workspace/create.html
{% extends "workspace/base.html" %} 

{% block create %}

<form action="{% url 'create' %}" method='POST' enctype='multipart/form-data' class='flex align-center justify-center mt-10'>
    {% csrf_token %}
    <div>
            <div class="mb-4">
                <label for="id_name">{{ form.name.label }}</label>
                {{ form.name }}
                <div class="text-danger">
                    {% for error in form.name.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="mb-4">
                <label for="id_photo">{{ form.photo.label }}</label>
                {{ form.photo }}
                <div class="text-danger">
                    {% for error in form.photo.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>


            <div class="mb-4">
                <label for="id_volume">{{ form.volume.label }}</label>
                {{ form.volume }}
                <div class="text-danger">
                    {% for error in form.volume.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="mb-4">
                <label for="id_model">{{ form.model.label }}</label>
                {{ form.model }}
                <div class="text-danger">
                    {% for error in form.model.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="mb-4">
                <label for="id_info">{{ form.info.label }}</label>
                {{ form.info }}
                <div class="text-danger">
                    {% for error in form.info.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="mb-4">
                <label for="id_price">{{ form.price.label }}</label>
                {{ form.price }}
                <div class="text-danger">
                    {% for error in form.price.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="mb-4">
                <label for="id_category">{{ form.category.label }}</label>
                {{ form.category }}
                <div class="text-danger">
                    {% for error in form.category.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="mb-4">
                <label for="id_teg">{{ form.teg.label }}</label>
                {{ form.teg }}
                <div class="text-danger">
                    {% for error in form.teg.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="mb-4">
                <label for="id_is_publish">{{ form.is_publish.label }}</label>
                {{ form.is_publish }}
                <div class="text-danger">
                    {% for error in form.is_publish.errors %}
                        <div>{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

        <button class='w-[450px] h-[50px] rounded-[5px] text-[22px] text-white bg-green-900 mt-2' type='submit'>Отправить</button>
    </div>
</form>



{% endblock create %}

templates/workspace/update.html
{% extends "workspace/base.html" %} {% block update %}

<form
  action="{% url 'create' %}"
  method="POST"
  enctype="multipart/form-data"
  class="flex align-center justify-center mt-10"
>
  {% csrf_token %}
  <div>
    <div class="mb-4">
      <label for="id_name">{{ form.name.label }}</label>
      {{ form.name }}
      <div class="text-danger">
        {% for error in form.name.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <div class="mb-4">
      <label for="id_photo">{{ form.photo.label }}</label>
      {{ form.photo }}
      <div class="text-danger">
        {% for error in form.photo.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <div class="mb-4">
      <label for="id_volume">{{ form.volume.label }}</label>
      {{ form.volume }}
      <div class="text-danger">
        {% for error in form.volume.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <div class="mb-4">
      <label for="id_model">{{ form.model.label }}</label>
      {{ form.model }}
      <div class="text-danger">
        {% for error in form.model.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <div class="mb-4">
      <label for="id_info">{{ form.info.label }}</label>
      {{ form.info }}
      <div class="text-danger">
        {% for error in form.info.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <div class="mb-4">
      <label for="id_price">{{ form.price.label }}</label>
      {{ form.price }}
      <div class="text-danger">
        {% for error in form.price.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <div class="mb-4">
      <label for="id_category">{{ form.category.label }}</label>
      {{ form.category }}
      <div class="text-danger">
        {% for error in form.category.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <div class="mb-4">
      <label for="id_teg">{{ form.teg.label }}</label>
      {{ form.teg }}
      <div class="text-danger">
        {% for error in form.teg.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <div class="mb-4">
      <label for="id_is_publish">{{ form.is_publish.label }}</label>
      {{ form.is_publish }}
      <div class="text-danger">
        {% for error in form.is_publish.errors %}
        <div>{{ error }}</div>
        {% endfor %}
      </div>
    </div>

    <button
      class="w-[450px] h-[50px] rounded-[5px] text-[22px] text-white bg-green-900 mt-2"
      type="submit"
    >
      Отправить
    </button>
  </div>
</form>

{% endblock update %}